### ISSUE TITLE
Welcome to sbemu-x

### ISSUE THREAD

**Issue by ghost** [sbemu-x/sbemu-x#1]
I would like to be able to share it with all friends who love the “DOS” system, and who want to contribute to implementing new functionalities to sbemu, and replacing, over time, software inherited from other projects with more open, less restrictive licenses, I would like to be able to invite the FreeDOS staff, if I'm interested in the project, @boeckmann, @PerditionC, @tkchia and also friends who have been in heated conversations for some time about sbemu, @volkertb @thp

**Comment by volkertb** [comment]
Great initiative! Happy to join. And when @crazii gets back on the radar, we should definitely encourage them to join forces with us as well.

What I can do is port my existing MR to set up GitHub Actions Workflow for this project. I have it as far that it builds `sbemu.exe` and packages it in a ready-to-flash bootable USB image with FreeDOS, whenever a change is committed or merged. I still need to enhance it so that it also builds the required [HDPMI32i fork](https://github.com/crazii/HX) and includes it in the image.

And then there is @Baron-von-Riedesel's [VSBHDA](https://github.com/Baron-von-Riedesel/VSBHDA) fork, which we might also want to keep an eye on, and perhaps also cooperate with, if everyone is open to that.

**Comment by boeckmann** [comment]
Nice! I still have a first gen Soundblaster Audigy Player card anywhere in my attic. I'll put it into my Pentium MMX 166 system and try to get it working. I think it even has toslink digital IO. Would be awesome getting that to work. I'll report back when I had time to test it.

**Comment by 4nd3r50ncr** [comment]
Finished
