### ISSUE TITLE
Redirect Adlib music to actual OPL2 or OPL3 hardware (OPL2LPT, OPL3LPT, RetroWave OPL3)

### ISSUE THREAD

**Issue by volkertb** [sbemu-x/sbemu-x#6]
In addition to the option of emulating FM synthesis in software, it might be nice to have an option to instead redirect FM music to an alternative device with an actual OPL2 or OPL3 synthesizer.

So SBEMU (or sbemu-x) would emulate an Adlib (Gold) or a Sound Blaster Pro 2 card, and would then redirect the FM music to a a device such as:

- OPL2LPT
- OPL3LPT
- RetroWave OPL3
- ~~A PCI sound card with actual OPL3 compatibility, such as the ESS Solo-1 (useful when installed in a more modern motherboard through a PCI->PCIe adapter, since the OPLx chip would have to be reached through a non-legacy I/O port, due to a lack of "subtractive decode" support)~~

Reasons why this might be useful:

- It's cool from a retro perspective, allowing as much use of "original hardware" as possible, using emulation only as a minimal layer where absolutely necessary
- On some older/slower post-ISA systems or retro laptops without integrated sound cards, redirecting to actual hardware would have a noticeably lower overhead than emulating an FM synthesizer in software
- For the purists (even though the [Nuked-OPL3](https://github.com/nukeykt/Nuked-OPL3) project has already managed to reach a "perfect" level of emulation, albeit at the expense of even  higher CPU utilization)

By rearchitecting the sbemu-x project to be modular, it would be possible to add both more emulated devices (for instance Gravis Ultrasound emulation) and support for more "backend drivers", which could either be emulators or redirectors to hardware such as the types listed above.

Thoughts?

**Comment by thp** [comment]
I do have an OPL2LPT that I could use for testing and this might be useful. However, we should probably enable Line In volume control (I'll probably do another PR after I have tested that CD Audio volume control works as expected), to not have to rely on an external mixer.

For using ESS Solo-1 for FM synth, I think you just need to disable the OPL-3 feature (`/OPL0`), and it should fall back to making port 0x338 being handled by the PCI card directly.

**Comment by volkertb** [comment]
> I do have an OPL2LPT that I could use for testing and this might be useful. However, we should probably enable Line In volume control (I'll probably do another PR after I have tested that CD Audio volume control works as expected), to not have to rely on an external mixer.

Good one. By the way, extensive volume control would be a whole other can of worms that we may probably want to open a dedicated issue for.

> For using ESS Solo-1 for FM synth, I think you just need to disable the OPL-3 feature (`/OPL0`), and it should fall back to making port 0x338 being handled by the PCI card directly.

I was referring to the use case of using such a card on a more modern motherboard without conventional PCI slots, having such a card plugged in through a PCI-to-PCIe adapter. In such cases, the OPL3 synthesizer on such a PCI card would not be reachable on its legacy port ports 0x338 and 0x339, but on some port higher than 0xFFF. This is due to the PCI bridge on newer motherboard not supporting a feature called "subtractive decode". For more details about this limitation in newer PCIe motherboard, see [this document](https://archive.org/details/33.-oxford-legacy-address-ranges) that explains why PCIe parallel port cards can't make their ports available at the classic standard I/O port addresses 0x378, 0x379 or 0x3BC. You can also find some discussions about the subtractive decode issue on Vogons.

Anyway, I would assume that the OPL3 synthesizer would still be reachable on a higher I/O port (some port above the legacy port range 0x0000- 0x0FFF), in which case an emulator like sbemu-x could make it work again simply by tapping I/O access to ports 0x338 and 0x339 and redirecting it to whatever alternate non-legacy port the OPL3 chip on the PCI card is listening on.

I'm making one assumption here, though: do a any resources listening on legacy I/O ports on a PCI card get made available through alternative non-legacy I/O ports at all? Or do those resources simply get masked if the PCI(e) bridge doesn't support subtractive decode? Or perhaps it depends in the PCI card? According to the Intel documentation quoted by Kamerat in [this post on Vogons](https://www.vogons.org/viewtopic.php?p=683361#p683361):

> 26.2 Overview
> ...
> • PCIe* Subtractive Decode is not supported
> — PCI can still be supported via a PCIe*-to-PCI bridge. However, legacy PCI devices (such as PCMCIA or non-plug-and-play device) that need subtractive decode are not supported.

That would imply that sbemu-x would have nothing to redirect OPL3 I/O to in such a case. The FM chip on the PCI card would simply be unreachable in such a motherboard.

We could ask around in Vogons to verify this, but in the meantime it would indeed be better to concentrate on devices such as the OPL3LPT and RetroWave OPL3 devices instead. By the way, in the case of OPLxLPT, we should look up the I/O port of the LPT ports in the BIOS Data Area (BDA), instead of assuming the legacy I/O ports 0x378, 0x379 or 0x3BC, since again, those wouldn't work in a system with a chipset that doesn't support subtractive decode.

**Comment by thp** [comment]
On a modern PCIe motherboard without any PCI backwards compatibility, why would you use a PCI Solo-1 compared to just SBEMU+OPL3 emulation in pure DOS or even just DOSBox-X or 86Box on your favorite modern operating system?

I personally don't care about the purists, and a "hardware purist" probably stays far away from SBEMU and uses some outdated ISA-based board with properly-aged ISA card. With that said, SBEMU's DOSBox-based OPL3 emulation is probably more "authentic" than many OPL clones out there, so a "FM purist" should be very happy with the existing software-based emulation already.

OPL2LPT and OPL3LPT is a different story, because it's modern hardware (still available?), and can work on laptops that don't have any PCI slots, and you might want to "offload" OPL processing on a machine that's struggling CPU-wise with OPL3 emulation, but still has a parallel port for interfacing such hardware. Plus, doing parallel port I/O isn't too involved in DOS (compared to trying to interface with a USB RetroWave?).

But any PCI machine either has enough backwards compatibility that you can just use a Solo-1's ESFM with proper PCI I/O ports, or new enough that the CPU is plenty fast for OPL3 software emulation or DOSBox-X/86Box on modern OSes.

**Comment by volkertb** [comment]
Fair reasoning. That use case is indeed obscure, with very low expected user interest, for the reasons you mention.

Let's leave that one (getting PCI cards with OPL3 compatibility working on newer motherboards) outside the scope of this issue, then. (I struck it through in the opening post of this issue.) :+1:

**Comment by xan1242** [comment]
Hi!

I'll just chime in because I'm somewhat interested in this topic.

I know that you pushed it aside and it's not in the scope, but if I catch some time, I'll be willing to experiment with this and try to make it work on a CMI8738.

I know for a fact that with the CMI8738 the FM works on a port 0x50 (that much is stated in its datasheet). I have vague memories of running Adlib Tracker 2 under native DOS with it and it worked (after punching in the custom port), but I can't remember if I was on an older AMD Phenom II / AM3+ board or on a MSI B350 Tomahawk board with a Ryzen.

Either way, my question is - since you capture the needed ports for emulation anyway, wouldn't it be possible to simply pass it through to port 0x50 of the card? Or am I missing something entirely here?

**Comment by hjnijlunsing** [comment]
Before passing OPL to the CMI8738 HW FM Synthesizer; did you get the CMI8738 to actually work with SBEMU-X? I tested four cards and all of them crashed with SBEMU-X.

**Comment by hjnijlunsing** [comment]
> On a modern PCIe motherboard without any PCI backwards compatibility, why would you use a PCI Solo-1 compared to just SBEMU+OPL3 emulation in pure DOS or even just DOSBox-X or 86Box on your favorite modern operating system?
> But any PCI machine either has enough backwards compatibility that you can just use a Solo-1's ESFM with proper PCI I/O ports, or new enough that the CPU is plenty fast for OPL3 software emulation or DOSBox-X/86Box on modern OSes.

The issue here is that ESS-Solo uses dubious PCI DMA techniques like DDMA, TDMA, WDMA and / or PC-LINK. 
Not all motherboard have this capability (mostly limited to VIA Chipsets it seems) and SBEMU seems to work fine without this ;-)

I have an HP T5710 Thin Client; with a ULI chipset (not VIA) and getting DOS SB Emulation to work with either to ESS-Solo1 on SB Live is a nightmare; but sbemu-x seems to work fine on the SBLive.

With the CPU Throtlled for certain DOS games (Bubble Bobble) ; it would definitely be better to have OPL pass to the Ess-Solo-1 FM chip; you would also get more predictable speed.

**Comment by xan1242** [comment]
> Before passing OPL to the CMI8738 HW FM Synthesizer; did you get the CMI8738 to actually work with SBEMU-X? I tested four cards and all of them crashed with SBEMU-X.

I didn't test anything yet, I'm just sharing my experience from a few years ago when I played with it fine on modern platforms.

If SBEMU-X doesn't work yet on it, that's a shame, but, I think there's hope for it. If building and debugging this isn't too hard, then I'll be sure to try to figure something out!

**Comment by Torinde** [comment]
Related: https://github.com/crazii/USBDDOS (a driver for RetroWave OPL3)
